# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_filer_get(self) -> None:
        """Test case for api_v1_filer_get

        Retrieve a filer by CIK.
        """
        pass

    def test_api_v1_filers_get(self) -> None:
        """Test case for api_v1_filers_get

        Retrieve unique filers.
        """
        pass

    def test_api_v1_filings_get(self) -> None:
        """Test case for api_v1_filings_get

        Retrieve 13F filings for all filers in the time range.
        """
        pass

    def test_api_v1_form_get(self) -> None:
        """Test case for api_v1_form_get

        Get SEC Form 13F.
        """
        pass

    def test_api_v1_forms_get(self) -> None:
        """Test case for api_v1_forms_get

        Retrieve SEC forms 13F for a filer.
        """
        pass

    def test_api_v1_funds_get(self) -> None:
        """Test case for api_v1_funds_get

        Retrieve unique companies.
        """
        pass


if __name__ == '__main__':
    unittest.main()
