# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.ticker_info import TickerInfo

class TestTickerInfo(unittest.TestCase):
    """TickerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TickerInfo:
        """Test TickerInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TickerInfo`
        """
        model = TickerInfo()
        if include_optional:
            return TickerInfo(
                cusip = '',
                ticker = '',
                company_name = ''
            )
        else:
            return TickerInfo(
        )
        """

    def testTickerInfo(self):
        """Test TickerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
