# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_filer import ApiV1Filer

class TestApiV1Filer(unittest.TestCase):
    """ApiV1Filer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1Filer:
        """Test ApiV1Filer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1Filer`
        """
        model = ApiV1Filer()
        if include_optional:
            return ApiV1Filer(
                cik = '',
                company_names = [
                    ''
                    ]
            )
        else:
            return ApiV1Filer(
        )
        """

    def testApiV1Filer(self):
        """Test ApiV1Filer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
