# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_fund import ApiV1Fund

class TestApiV1Fund(unittest.TestCase):
    """ApiV1Fund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1Fund:
        """Test ApiV1Fund
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1Fund`
        """
        model = ApiV1Fund()
        if include_optional:
            return ApiV1Fund(
                name = '',
                cik = ''
            )
        else:
            return ApiV1Fund(
        )
        """

    def testApiV1Fund(self):
        """Test ApiV1Fund"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
