# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_form import ApiV1Form

class TestApiV1Form(unittest.TestCase):
    """ApiV1Form unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1Form:
        """Test ApiV1Form
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1Form`
        """
        model = ApiV1Form()
        if include_optional:
            return ApiV1Form(
                url = '',
                accession_number = '',
                submission_type = '',
                public_document_count = 56,
                period_of_report = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                filed_as_of_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_as_of_change = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                effectiveness_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                cik = '',
                company_name = '',
                irs_number = '',
                state_of_incorporation = '',
                fiscal_year_end = '',
                form_type = '',
                sec_act = '',
                sec_file_number = '',
                film_number = '',
                business_address = '',
                business_phone = '',
                table_value_total = 56,
                table_entry_total = 56,
                is_amendment = True,
                amendment_type = '',
                conf_denied_expired = True,
                conf_date_denied_expired = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                amendment_date_reported = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return ApiV1Form(
        )
        """

    def testApiV1Form(self):
        """Test ApiV1Form"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
