# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_form_entry import ApiV1FormEntry

class TestApiV1FormEntry(unittest.TestCase):
    """ApiV1FormEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1FormEntry:
        """Test ApiV1FormEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1FormEntry`
        """
        model = ApiV1FormEntry()
        if include_optional:
            return ApiV1FormEntry(
                accession_number = '',
                cik = '',
                name_of_issuer = '',
                title_of_class = '',
                cusip = '',
                value = 56,
                ssh_prnamt = 56,
                ssh_prnamt_type = '',
                investment_discretion = '',
                voting_authority_sole = 56,
                voting_authority_shared = 56,
                voting_authority_none = 56
            )
        else:
            return ApiV1FormEntry(
        )
        """

    def testApiV1FormEntry(self):
        """Test ApiV1FormEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
